Traceback (most recent call last):
  File "/home/pi/reset.py", line 6, in <module>
    system("res")
NameError: name 'system' is not defined
Traceback (most recent call last):
  File "/home/pi/reset.py", line 6, in <module>
    system("res")
NameError: name 'system' is not defined
